version: "3.10"
services:
  ray:
    build:
      context: .
      dockerfile: Dockerfile.ray
    ports:
      - "8000:8000"
    networks:
      - app_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    networks:
      - app_network
    environment:
    - API_URL=http://ray:8000/
    

networks:
  app_network:
    driver: bridge

