# Base image
FROM python:3.10-slim

# Update and install necessary packages
RUN apt update -y && apt install awscli -y

# Set working directory
WORKDIR /app

# Copy application files
COPY . .

# Install dependencies
RUN pip install -r app/requirements.txt

# Expose Streamlit port
EXPOSE 8501

# Start Streamlit
CMD ["streamlit", "run", "app/app.py", "--server.port=8501", "--server.enableCORS=false", "server.enableXsrfProtection = false","--server.address=0.0.0.0"]
