# Base image
FROM python:3.10-slim

# Update and install necessary packages
RUN apt update -y && apt install awscli -y

# Set working directory
WORKDIR /app

# Copy application files
COPY . .

# Install dependencies
RUN pip install -r main/requirements.txt

# Expose Ray Serve port
EXPOSE 8000

# Start Ray Serve
CMD ["serve", "run", "main.main:endpoint_app"]
